export const EVENT_TYPE_KEYWORDS = [
  "Conference",
  "Tradeshow",
  "Meeting",
  "Expo",
  "Symposium",
  "Convention",
  "Summit",
  "Sales Meeting",
  "Financial Meeting",
  "Congress",
  "Consumer Show",
  "Association",
  "Webinar",
  "Clinical Meeting",
  "Show",
  "Training Summit",
  "Annual Meeting",
  "Forums",
  "Meetings",
  "Event",
  "Exposition",
  "Users Group",
  "Compliance",
  "Food Event",
  "Festival",
  "Wine Event",
] as const

export const EXCEL_EXPORT_COLUMNS = [
  "Event Name",
  "Location",
  "Contact Name",
  "Contact Title",
  "Phone",
  "Email",
  "Date of Event",
  "Status",
] as const
